// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inxlpojledyyrcosfyxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlueGxwb2psZWR5eXJjb3NmeXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDkxNzYsImV4cCI6MjA2OTQyNTE3Nn0.Lzr4byknW57wsP1AvEBqiAk_gCYoQdtP7uaNuqr1NFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});